TITLE = "Small Loop"
MAPFILE = "map.txt"

GREEN = (0, 100, 0)
GREY = (100, 100, 100)
BLACK = (0, 0, 0)

SCREEN_WIDTH = 300
SCREEN_HEIGHT = 300

NUMBER_OF_BLOCKS_WIDE = 6
NUMBER_OF_BLOCKS_HIGH = 6

BLOCK_HEIGHT = round(SCREEN_HEIGHT / NUMBER_OF_BLOCKS_HIGH)
BLOCK_WIDTH = round(SCREEN_WIDTH / NUMBER_OF_BLOCKS_WIDE)
